# Use the official Golang image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the local package files to the container's workspace
COPY . /app

# Build the Go application
RUN go build -o main ./main.go

# Expose the port that the application will run on
EXPOSE 8080

# Command to run the executable
CMD ["./main"]