// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2024-08-12 13:41:10.520789075 -0300 -03 m=+9.046505155

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "Esse e um teste pratico para a vaga Flutter/Golang da empresa X.",
        "title": "TESTE PRATICO FLUTTER/GOLANG API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.1"
    },
    "host": "localhost:8000",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/courses/add-students": {
            "post": {
                "description": "Add students to course",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Add students to course",
                "parameters": [
                    {
                        "description": "Students and Course information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/application.CourseStudentReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Student add successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/courses/create": {
            "post": {
                "description": "Create new course",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Create course",
                "parameters": [
                    {
                        "description": "Course information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/application.CourseReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Course created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/courses/list": {
            "get": {
                "description": "List all course",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "List all course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit the number of results (default is 10)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of courses",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/courses/list-students-course": {
            "get": {
                "description": "List all course students",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "List all course students",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Codigo do curso",
                        "name": "search",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of courses",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/courses/update": {
            "patch": {
                "description": "Update course",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Update course",
                "parameters": [
                    {
                        "description": "Course information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/application.CourseReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Course updated successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/students/create": {
            "post": {
                "description": "Create new student",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Create student",
                "parameters": [
                    {
                        "description": "Student information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/application.StudentReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Student created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/students/list": {
            "get": {
                "description": "List all students",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "List all students",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit the number of results (default is 10)",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Student name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of students",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        },
        "/students/update": {
            "patch": {
                "description": "Update student",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Update student",
                "parameters": [
                    {
                        "description": "Student information",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/application.StudentReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "Timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for the request",
                        "name": "Sign",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Unique UUID for the request",
                        "name": "Nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API version",
                        "name": "App-Version",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Student updated successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/responses.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "application.CourseReq": {
            "type": "object",
            "required": [
                "description",
                "ementa"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "ementa": {
                    "type": "string"
                }
            }
        },
        "application.CourseStudentReq": {
            "type": "object",
            "required": [
                "code_course",
                "code_student"
            ],
            "properties": {
                "code_course": {
                    "type": "integer"
                },
                "code_student": {
                    "type": "integer"
                }
            }
        },
        "application.StudentReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "code": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "responses.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
